# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.cache/wt [current_project]
set_property parent.project_path /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3.xci
set_property is_locked true [get_files /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ddr3 -part xc7a35ticsg324-1L -mode out_of_context

rename_ref -prefix_all ddr3_

write_checkpoint -force -noxdef ddr3.dcp

catch { report_utilization -file ddr3_utilization_synth.rpt -pb ddr3_utilization_synth.pb }

if { [catch {
  file copy -force /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.runs/ddr3_synth_1/ddr3.dcp /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.ip_user_files/ip/ddr3]} {
  catch { 
    file copy -force /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3_stub.v /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.ip_user_files/ip/ddr3
  }
}

if {[file isdir /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.ip_user_files/ip/ddr3]} {
  catch { 
    file copy -force /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.srcs/sources_1/ip/ddr3/ddr3_stub.vhdl /home/ckdur/Documents/mriscv_vivado_arty/mriscv_vivado.ip_user_files/ip/ddr3
  }
}
